<?php
    // DATABASE
    require_once ($page['path'].'_classes/Data.php');
    require_once ($page['path'].'_classes/Content.php');
    require_once ($page['path'].'_classes/Contact_Method.php');
    require_once ($page['path'].'_classes/Name_Suffix.php');
    require_once ($page['path'].'_classes/Salutation.php');
    require_once ($page['path'].'_classes/State.php');
    require_once ($page['path'].'_classes/Prospect.php');
    require_once ($page['path'].'_classes/Log.php');
    require_once ($page['path'].'_classes/User.php');
    require_once ($page['path'].'_classes/Person.php');
    require_once ($page['path'].'_classes/Profile.php');
    require_once ($page['path'].'_classes/Contact.php');
    // HELPERS
    require_once ($page['path'].'_classes/Status.php');
    require_once ($page['path'].'_classes/Crud.php');
    require_once ($page['path'].'_classes/Format.php');
    require_once ($page['path'].'_classes/Input.php');
    require_once ($page['path'].'_classes/Link.php');
    require_once ($page['path'].'_classes/Validation.php');