<?php
    // CRUD
    require_once ($page['path'].'_functions/create.php');
    require_once ($page['path'].'_functions/read.php');
    require_once ($page['path'].'_functions/update.php');
    require_once ($page['path'].'_functions/delete.php');
    // STRINGS
    require_once ($page['path'].'_functions/formatEmailLink.php');
    require_once ($page['path'].'_functions/formatOutsideLink.php');
    require_once ($page['path'].'_functions/formatPhone.php');
    require_once ($page['path'].'_functions/formatPostUS.php');
    require_once ($page['path'].'_functions/formatDriversLicense.php');
    require_once ($page['path'].'_functions/formatSSN.php');
    require_once ($page['path'].'_functions/returnFullNamePlus.php');
    // INPUTS
    require_once ($page['path'].'_functions/ddlDates.php');
    require_once ($page['path'].'_functions/ddlOptions.php');
    require_once ($page['path'].'_functions/rblGender.php');
    require_once ($page['path'].'_functions/rblOptions.php');
    require_once ($page['path'].'_functions/rblTrueFalse.php');
    // OTHER
    require_once ($page['path'].'_functions/redirect.php');
    require_once ($page['path'].'_functions/returnAlreadyCheck.php');
    require_once ($page['path'].'_functions/returnSort.php');
    require_once ($page['path'].'_functions/returnTHEAD.php');